import './globals.css'
import Link from 'next/link'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'
import { authOptions } from "/pages/api/auth/[...nextauth]"
import { getServerSession } from "next-auth/next"

export const metadata = {
  title: 'next-forum',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html>
      <body>
        <div className="navbar">
          <Link href="/" className='Logo'>Forum</Link>
          <Link href="/list" >List</Link>
          {
            session
            ? <LogoutBtn/>
            : <LoginBtn/>
          }
          {
            session
            ? <Link href="/">회원정보</Link>
            : <Link href="/register">회원가입</Link>
          }
        </div>
          {children}
      </body>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  )
}
